
export const FROM_AIRPORT_LIST = {
    ABI:'Abilene Regional',
    ALB:'Albany International',
    ABQ:'Albuquerque International Sunport',
    AEX:'Alexandria International',
    AGS:'Augusta Regional at Bush Field',
    AUS:'Austin - Bergstrom International',
    BWI:'Baltimore/Washington International Thurgood Marshall',
    BGR:'Bangor International',
    BTR:'Baton Rouge Metropolitan/Ryan Field',
    LIT:'Bill and Hillary Clinton Nat Adams Field',
    BHM:'Birmingham-Shuttlesworth International',
    BUR:'Bob Hope',
    BOI:'Boise Air Terminal',
    BDL:'Bradley International',
    BRO:'Brownsville South Padre Island International',
    BQK:'Brunswick Golden Isles',
    BUF:'Buffalo Niagara International',
    BTV:'Burlington International',
    LAN:'Capital Region International',
    CPR:'Casper/Natrona County International',
    CDC:'Cedar City Regional',
    CHS:'Charleston AFB/International',
    CLT:'Charlotte Douglas International',
    CYS:'Cheyenne Regional/Jerry Olson Field',
    MDW:'Chicago Midway International',
    ORD:'Chicago O Hare International',
    CVG:'Cincinnati/Northern Kentucky International',
    COS:'City of Colorado Springs Municipal',
    CLE:'Cleveland-Hopkins International',
    EWN:'Coastal Carolina Regional',
    CAE:'Columbia Metropolitan',
    COU:'Columbia Regional',
    CRP:'Corpus Christi International',
    DAL:'Dallas Love Field',
    DFW:'Dallas/Fort Worth International',
    MSN:'Dane County Regional-Truax Field',
    HNL:'Daniel K Inouye International',
    DRT:'Del Rio International',
    DEN:'Denver International',
    DSM:'Des Moines International',
    DTW:'Detroit Metro Wayne County',
    DHN:'Dothan Regional',
    DLH:'Duluth International',
    DRO:'Durango La Plata County',
    GGG:'East Texas Regional',
    CLL:'Easterwood Field',
    VPS:'Eglin AFB Destin Fort Walton Beach',
    ELP:'El Paso International',
    KOA:'Ellison Onizuka Kona International at Keahole',
    OMA:'Eppley Airfield',
    FAI:'Fairbanks International',
    INL:'Falls International Einarson Field',
    FLO:'Florence Regional',
    FLL:'Fort Lauderdale-Hollywood International',
    FSM:'Fort Smith Regional',
    FAT:'Fresno Yosemite International',
    GNV:'Gainesville Regional',
    GCK:'Garden City Regional',
    MKE:'General Mitchell International',
    IAH:'George Bush Intercontinental/Houston',
    GRR:'Gerald R. Ford International',
    GFK:'Grand Forks International',
    GTF:'Great Falls International',
    ROC:'Greater Rochester International',
    GRB:'Green Bay Austin Straubel International',
    MDT:'Harrisburg International',
    ATL:'Hartsfield-Jackson Atlanta International',
    HLN:'Helena Regional',
    ITO:'Hilo International',
    IND:'Indianapolis International',
    BPT:'Jack Brooks Regional',
    JAN:'Jackson Medgar Wiley Evers International',
    JAX:'Jacksonville International',
    DAY:'James M Cox/Dayton International',
    JFK:'John F. Kennedy International',
    CMH:'John Glenn Columbus International',
    SNA:'John Wayne Airport-Orange County',
    OGG:'Kahului Airport',
    MCI:'Kansas City International',
    JHM:'Kapalua Airport',
    KTN:'Ketchikan International',
    EYW:'Key West International',
    LGA:'LaGuardia',
    LFT:'Lafayette Regional Paul Fournet Field',
    LCH:'Lake Charles Regional',
    LNY:'Lanai Airport',
    LRD:'Laredo International',
    HOB:'Lea County Regional',
    LIH:'Lihue Airport',
    LNK:'Lincoln Airport',
    BOS:'Logan International',
    LGB:'Long Beach Airport',
    ISP:'Long Island MacArthur',
    LAX:'Los Angeles International',
    MSY:'Louis Armstrong New Orleans International',
    CHA:'Lovell Field',
    LBB:'Lubbock Preston Smith International',
    MFE:'McAllen Miller International',
    LAS:'McCarran International',
    TYS:'McGhee Tyson',
    BFL:'Meadows Field',
    MLB:'Melbourne International',
    MEM:'Memphis International',
    OAK:'Metropolitan Oakland International',
    MIA:'Miami International',
    MAF:'Midland International Air and Space Port',
    MSP:'Minneapolis-St Paul International',
    MOT:'Minot International',
    MOB:'Mobile Regional',
    MKK:'Molokai',
    MLU:'Monroe Regional',
    MYR:'Myrtle Beach International',
    ACK:'Nantucket Memorial',
    BNA:'Nashville International',
    SWF:'New York Stewart International',
    EWR:'Newark Liberty International',
    PHF:'Newport News/Williamsburg International',
    ORF:'Norfolk International',
    SJC:'Norman Y. Mineta San Jose International',
    OGS:'Ogdensburg International',
    ONT:'Ontario International',
    MCO:'Orlando International',
    PBI:'Palm Beach International',
    PSP:'Palm Springs International',
    PNS:'Pensacola International',
    PHL:'Philadelphia International',
    PHX:'Phoenix Sky Harbor International',
    PIT:'Pittsburgh International',
    PBG:'Plattsburgh International',
    PDX:'Portland International',
    PWM:'Portland International Jetport',
    PRC:'Prescott Regional Ernest A Love Field',
    PQI:'Presque Isle International',
    PUB:'Pueblo Memorial',
    RDU:'Raleigh-Durham International',
    HIB:'Range Regional',
    RNO:'Reno/Tahoe International',
    RIC:'Richmond International',
    AMA:'Rick Husband Amarillo International',
    GRK:'Robert Gray AAF',
    DCA:'Ronald Reagan Washington National',
    ROW:'Roswell International Air Center',
    SMF:'Sacramento International',
    SBY:'Salisbury-Ocean City/Wicomico Regional',
    SLC:'Salt Lake City International',
    SJT:'San Angelo Regional/Mathis Field',
    SAT:'San Antonio International',
    SAN:'San Diego International',
    SFO:'San Francisco International',
    SAF:'Santa Fe Municipal',
    SAV:'Savannah/Hilton Head International',
    MQT:'Sawyer International',
    SEA:'Seattle/Tacoma International',
    SPS:'Sheppard AFB/Wichita Falls Municipal',
    SHV:'Shreveport Regional',
    SUX:'Sioux Gateway Brig Gen Bud Day Field',
    SIT:'Sitka Rocky Gutierrez',
    PAE:'Snohomish County',
    RSW:'Southwest Florida International',
    ABY:'Southwest Georgia Regional',
    GEG:'Spokane International',
    STL:'St Louis Lambert International',
    SCK:'Stockton Metropolitan',
    SYR:'Syracuse Hancock International',
    TLH:'Tallahassee International',
    TPA:'Tampa International',
    ANC:'Ted Stevens Anchorage International',
    TXK:'Texarkana Regional-Webb Field',
    PVD:'Theodore Francis Green State',
    TUS:'Tucson International',
    TUL:'Tulsa International',
    TYR:'Tyler Pounds Regional',
    HRL:'Valley International',
    ACT:'Waco Regional',
    IAD:'Washington Dulles International',
    ART:'Watertown International',
    HPN:'Westchester County',
    ICT:'Wichita Dwight D Eisenhower National',
    OKC:'Will Rogers World',
    HOU:'William P Hobby',
    IPT:'Williamsport Regional',
    ILM:'Wilmington International',
    YUM:'Yuma MCAS/Yuma International',
}

export const TO_AIRPORT_LIST = {
    ABI:'Abilene Regional',
    ALB:'Albany International',
    ABQ:'Albuquerque International Sunport',
    AEX:'Alexandria International',
    AGS:'Augusta Regional at Bush Field',
    AUS:'Austin - Bergstrom International',
    BWI:'Baltimore/Washington International Thurgood Marshall',
    BGR:'Bangor International',
    BTR:'Baton Rouge Metropolitan/Ryan Field',
    LIT:'Bill and Hillary Clinton Nat Adams Field',
    BHM:'Birmingham-Shuttlesworth International',
    BUR:'Bob Hope',
    BOI:'Boise Air Terminal',
    BDL:'Bradley International',
    BRO:'Brownsville South Padre Island International',
    BQK:'Brunswick Golden Isles',
    BUF:'Buffalo Niagara International',
    BTV:'Burlington International',
    LAN:'Capital Region International',
    CPR:'Casper/Natrona County International',
    CDC:'Cedar City Regional',
    CHS:'Charleston AFB/International',
    CLT:'Charlotte Douglas International',
    CYS:'Cheyenne Regional/Jerry Olson Field',
    MDW:'Chicago Midway International',
    ORD:'Chicago O Hare International',
    CVG:'Cincinnati/Northern Kentucky International',
    COS:'City of Colorado Springs Municipal',
    CLE:'Cleveland-Hopkins International',
    EWN:'Coastal Carolina Regional',
    CAE:'Columbia Metropolitan',
    COU:'Columbia Regional',
    CRP:'Corpus Christi International',
    DAL:'Dallas Love Field',
    DFW:'Dallas/Fort Worth International',
    MSN:'Dane County Regional-Truax Field',
    HNL:'Daniel K Inouye International',
    DRT:'Del Rio International',
    DEN:'Denver International',
    DSM:'Des Moines International',
    DTW:'Detroit Metro Wayne County',
    DHN:'Dothan Regional',
    DLH:'Duluth International',
    DRO:'Durango La Plata County',
    GGG:'East Texas Regional',
    CLL:'Easterwood Field',
    VPS:'Eglin AFB Destin Fort Walton Beach',
    ELP:'El Paso International',
    KOA:'Ellison Onizuka Kona International at Keahole',
    OMA:'Eppley Airfield',
    FAI:'Fairbanks International',
    INL:'Falls International Einarson Field',
    FLO:'Florence Regional',
    FLL:'Fort Lauderdale-Hollywood International',
    FSM:'Fort Smith Regional',
    FAT:'Fresno Yosemite International',
    GNV:'Gainesville Regional',
    GCK:'Garden City Regional',
    MKE:'General Mitchell International',
    IAH:'George Bush Intercontinental/Houston',
    GRR:'Gerald R. Ford International',
    GFK:'Grand Forks International',
    GTF:'Great Falls International',
    ROC:'Greater Rochester International',
    GRB:'Green Bay Austin Straubel International',
    MDT:'Harrisburg International',
    ATL:'Hartsfield-Jackson Atlanta International',
    HLN:'Helena Regional',
    ITO:'Hilo International',
    IND:'Indianapolis International',
    BPT:'Jack Brooks Regional',
    JAN:'Jackson Medgar Wiley Evers International',
    JAX:'Jacksonville International',
    DAY:'James M Cox/Dayton International',
    JFK:'John F. Kennedy International',
    CMH:'John Glenn Columbus International',
    SNA:'John Wayne Airport-Orange County',
    JNU:'Juneau International',
    OGG:'Kahului Airport',
    MCI:'Kansas City International',
    JHM:'Kapalua Airport',
    KTN:'Ketchikan International',
    EYW:'Key West International',
    LGA:'LaGuardia',
    LFT:'Lafayette Regional Paul Fournet Field',
    LCH:'Lake Charles Regional',
    LNY:'Lanai Airport',
    LRD:'Laredo International',
    HOB:'Lea County Regional',
    LIH:'Lihue Airport',
    LNK:'Lincoln Airport',
    BOS:'Logan International',
    LGB:'Long Beach Airport',
    ISP:'Long Island MacArthur',
    LAX:'Los Angeles International',
    MSY:'Louis Armstrong New Orleans International',
    CHA:'Lovell Field',
    LBB:'Lubbock Preston Smith International',
    MFE:'McAllen Miller International',
    LAS:'McCarran International',
    TYS:'McGhee Tyson',
    BFL:'Meadows Field',
    MLB:'Melbourne International',
    MEM:'Memphis International',
    OAK:'Metropolitan Oakland International',
    MIA:'Miami International',
    MAF:'Midland International Air and Space Port',
    MSP:'Minneapolis-St Paul International',
    MOT:'Minot International',
    MOB:'Mobile Regional',
    MKK:'Molokai',
    MLU:'Monroe Regional',
    MYR:'Myrtle Beach International',
    ACK:'Nantucket Memorial',
    BNA:'Nashville International',
    SWF:'New York Stewart International',
    EWR:'Newark Liberty International',
    PHF:'Newport News/Williamsburg International',
    ORF:'Norfolk International',
    SJC:'Norman Y. Mineta San Jose International',
    OGS:'Ogdensburg International',
    ONT:'Ontario International',
    MCO:'Orlando International',
    PBI:'Palm Beach International',
    PSP:'Palm Springs International',
    PNS:'Pensacola International',
    PHL:'Philadelphia International',
    PHX:'Phoenix Sky Harbor International',
    PIT:'Pittsburgh International',
    PBG:'Plattsburgh International',
    PDX:'Portland International',
    PWM:'Portland International Jetport',
    PRC:'Prescott Regional Ernest A Love Field',
    PQI:'Presque Isle International',
    PUB:'Pueblo Memorial',
    RDU:'Raleigh-Durham International',
    HIB:'Range Regional',
    RNO:'Reno/Tahoe International',
    RIC:'Richmond International',
    AMA:'Rick Husband Amarillo International',
    GRK:'Robert Gray AAF',
    DCA:'Ronald Reagan Washington National',
    ROW:'Roswell International Air Center',
    SMF:'Sacramento International',
    SBY:'Salisbury-Ocean City/Wicomico Regional',
    SLC:'Salt Lake City International',
    SJT:'San Angelo Regional/Mathis Field',
    SAT:'San Antonio International',
    SAN:'San Diego International',
    SFO:'San Francisco International',
    SAF:'Santa Fe Municipal',
    SAV:'Savannah/Hilton Head International',
    MQT:'Sawyer International',
    SEA:'Seattle/Tacoma International',
    SPS:'Sheppard AFB/Wichita Falls Municipal',
    SHV:'Shreveport Regional',
    SUX:'Sioux Gateway Brig Gen Bud Day Field',
    SIT:'Sitka Rocky Gutierrez',
    PAE:'Snohomish County',
    RSW:'Southwest Florida International',
    ABY:'Southwest Georgia Regional',
    GEG:'Spokane International',
    STL:'St Louis Lambert International',
    SCK:'Stockton Metropolitan',
    SYR:'Syracuse Hancock International',
    TLH:'Tallahassee International',
    TPA:'Tampa International',
    ANC:'Ted Stevens Anchorage International',
    TXK:'Texarkana Regional-Webb Field',
    PVD:'Theodore Francis Green State',
    TUS:'Tucson International',
    TUL:'Tulsa International',
    TYR:'Tyler Pounds Regional',
    HRL:'Valley International',
    ACT:'Waco Regional',
    IAD:'Washington Dulles International',
    ART:'Watertown International',
    HPN:'Westchester County',
    ICT:'Wichita Dwight D Eisenhower National',
    OKC:'Will Rogers World',
    HOU:'William P Hobby',
    IPT:'Williamsport Regional',
    ILM:'Wilmington International',
    YUM:'Yuma MCAS/Yuma International',
}