
export const FROM_AIRPORT_LIST = {
    ONT:'Ontario International',
    ORF:'Norfolk International',
    PBI:'Palm Beach International',
    PDX:'Portland International',
    PHL:'Philadelphia International',
    PHX:'Phoenix Sky Harbor International',
    PIT:'Pittsburgh International',
    PNS:'Pensacola International',
    PVD:'Theodore Francis Green State',
    PWM:'Portland International Jetport',
    RDU:'Raleigh-Durham International',
    RIC:'Richmond International',
    RNO:'Reno/Tahoe International',
    ROC:'Greater Rochester International',
    RSW:'Southwest Florida International',
    SAN:'San Diego International',
    SAT:'San Antonio International',
    SEA:'Seattle/Tacoma International',
    SFO:'San Francisco International',
    SJC:'Norman Y. Mineta San Jose International',
    SLC:'Salt Lake City International',
    SMF:'Sacramento International',
    SNA:'John Wayne Airport-Orange County',
    STL:'St Louis Lambert International',
    TPA:'Tampa International',
    TUL:'Tulsa International',
    TUS:'Tucson International',
    ABQ:'Albuquerque International Sunport',
    ALB:'Albany International',
    AMA:'Rick Husband Amarillo International',
    ATL:'Hartsfield-Jackson Atlanta International',
    AUS:'Austin - Bergstrom International',
    DAL:'Dallas Love Field',
    MSY:'Louis Armstrong New Orleans International',
    OAK:'Metropolitan Oakland International',
    OGG:'Kahului Airport',
    OKC:'Will Rogers World',
    OMA:'Eppley Airfield',
    BDL:'Bradley International',
    BHM:'Birmingham-Shuttlesworth International',
    BNA:'Nashville International',
    BOI:'Boise Air Terminal',
    BOS:'Logan International',
    BUF:'Buffalo Niagara International',
    BUR:'Bob Hope',
    BWI:'Baltimore/Washington International Thurgood Marshall',
    CHS:'Charleston AFB/International',
    CLE:'Cleveland-Hopkins International',
    CLT:'Charlotte Douglas International',
    CMH:'John Glenn Columbus International',
    CRP:'Corpus Christi International',
    CVG:'Cincinnati/Northern Kentucky International',
    DCA:'Ronald Reagan Washington National',
    DEN:'Denver International',
    DSM:'Des Moines International',
    DTW:'Detroit Metro Wayne County',
    ELP:'El Paso International',
    FLL:'Fort Lauderdale-Hollywood International',
    GEG:'Spokane International',
    GRR:'Gerald R. Ford International',
    HNL:'Daniel K Inouye International',
    HOU:'William P Hobby',
    HRL:'Valley International',
    IAD:'Washington Dulles International',
    ICT:'Wichita Dwight D Eisenhower National',
    IND:'Indianapolis International',
    ISP:'Long Island MacArthur',
    ITO:'Hilo International',
    JAX:'Jacksonville International',
    KOA:'Ellison Onizuka Kona International at Keahole',
    LAS:'McCarran International',
    LAX:'Los Angeles International',
    LBB:'Lubbock Preston Smith International',
    LGA:'LaGuardia',
    LGB:'Long Beach Airport',
    LIH:'Lihue Airport',
    LIT:'Bill and Hillary Clinton Nat Adams Field',
    MAF:'Midland International Air and Space Port',
    MCI:'Kansas City International',
    MCO:'Orlando International',
    MDW:'Chicago Midway International',
    MEM:'Memphis International',
    MKE:'General Mitchell International',
    MSP:'Minneapolis-St Paul International',
    DFW:'Dallas/Fort Worth International',
    DLH:'Duluth International',
    ORD: "Chicago O'Hare International",
    BRO:'Brownsville South Padre Island International',
    IAH:'George Bush Intercontinental/Houston',
    GGG:'East Texas Regional',
    JFK:'John F. Kennedy International',
    BTR:'Baton Rouge Metropolitan/Ryan Field',
    MIA:'Miami International',
    ILM:'Wilmington International',
    DAY:'James M Cox/Dayton International',
    SHV:'Shreveport Regional',
    COS:'City of Colorado Springs Municipal',
    FSM:'Fort Smith Regional',
    GRK:'Robert Gray AAF',
    MQT:'Sawyer International',
    EWR:'Newark Liberty International',
    MDT:'Harrisburg International',
    SYR:'Syracuse Hancock International',
    CLL:'Easterwood Field',
    TYR:'Tyler Pounds Regional',
    GCK:'Garden City Regional',
    MLU:'Monroe Regional',
    GRB:'Green Bay Austin Straubel International',
    TXK:'Texarkana Regional-Webb Field',
    EYW:'Key West International',
    TLH:'Tallahassee International',
    LFT:'Lafayette Regional Paul Fournet Field',
    MFE:'McAllen Miller International',
    CAE:'Columbia Metropolitan',
    SUX:'Sioux Gateway Brig Gen Bud Day Field',
    TYS:'McGhee Tyson',
    MSN:'Dane County Regional-Truax Field',
    SJT:'San Angelo Regional/Mathis Field',
    SPS:'Sheppard AFB/Wichita Falls Municipal',
    ABI:'Abilene Regional',
    LRD:'Laredo International',
    LCH:'Lake Charles Regional',
    JAN:'Jackson Medgar Wiley Evers International',
    BTV:'Burlington International',
    MOB:'Mobile Regional',
    SAV:'Savannah/Hilton Head International',
    MKK:'Molokai',
    LNY:'Lanai Airport',
    JHM:'Kapalua Airport',
    CHA:'Lovell Field',
    EWN:'Coastal Carolina Regional',
    BGR:'Bangor International',
    AGS:'Augusta Regional at Bush Field',
    HPN:'Westchester County',
    PHF:'Newport News/Williamsburg International',
    VPS:'Eglin AFB Destin Fort Walton Beach',
    GNV:'Gainesville Regional',
    GTF:'Great Falls International',
    PSP:'Palm Springs International',
    BLI:'Bellingham International',
    PAE:'Snohomish County',
    HLN:'Helena Regional',
    FAT:'Fresno Yosemite International',
    MYR:'Myrtle Beach International',
    BFM:'Mobile Downtown',
    TTN:'Trenton Mercer',
    ACY:'Atlantic City International',
    ANC:'Ted Stevens Anchorage International',
    MLB:'Melbourne International',
    FAI:'Fairbanks International',
    YUM:'Yuma MCAS/Yuma International',
    COU:'Columbia Regional',
    SAF:'Santa Fe Municipal',
    ROW:'Roswell International Air Center',
    CYS:'Cheyenne Regional/Jerry Olson Field',
    BQK:'Brunswick Golden Isles',
    GFK:'Grand Forks International',
    ABY:'Southwest Georgia Regional',
    MOT:'Minot International',
    LAN:'Capital Region International',
    LNK:'Lincoln Airport',
    DHN:'Dothan Regional',
    INL:'Falls International Einarson Field',
    CPR:'Casper/Natrona County International',
    CDC:'Cedar City Regional',
    HIB:'Range Regional',
    SWF:'New York Stewart International',
    OGS:'Ogdensburg International',
    PUB:'Pueblo Memorial',
    PBG:'Plattsburgh International',
    SCK:'Stockton Metropolitan',
    PRC:'Prescott Regional Ernest A Love Field',
    BFL:'Meadows Field',
    HOB:'Lea County Regional',
    DRO:'Durango La Plata County',
    ACT:'Waco Regional',
    AEX:'Alexandria International',
    IAG:'Niagara Falls International',
    PQI:'Presque Isle International',
    SFB:'Orlando Sanford International',
    PIE:'St Pete Clearwater International',
    LCK:'Rickenbacker International',
    BLV:'Scott AFB/MidAmerica',
    DRT:'Del Rio International',
    ADQ:'Kodiak Airport',
    BET:'Bethel Airport',
    BRW:'Wiley Post/Will Rogers Memorial',
    SCC:'Deadhorse Airport',
    KTN:'Ketchikan International',
    JNU:'Juneau International',
    SIT:'Sitka Rocky Gutierrez',
    OME:'Nome Airport',
    OTZ:'Ralph Wien Memorial',
    ADK:'Adak',
    CDV:'Merle K Mudhole Smith',
    YAK:'Yakutat Airport',
    ART:'Watertown International',
    FLO:'Florence Regional',
    SBY:'Salisbury-Ocean City/Wicomico Regional',
    IPT:'Williamsport Regional',
    BPT:'Jack Brooks Regional',
    CDB:'Cold Bay Airport',
    DLG:'Dillingham Airport',
    AKN:'King Salmon Airport',
    ACK:'Nantucket Memorial'
}


export const TO_AIRPORT_LIST = {
    SFO:'San Francisco International',
    SJC:'Norman Y. Mineta San Jose International',
    SMF:'Sacramento International',
    BWI:'Baltimore/Washington International Thurgood Marshall',
    MCO:'Orlando International',
    MDW:'Chicago Midway International',
    ATL:'Hartsfield-Jackson Atlanta International',
    ISP:'Long Island MacArthur',
    BUR:'Bob Hope',
    DAL:'Dallas Love Field',
    DEN:'Denver International',
    LAS:'McCarran International',
    LAX:'Los Angeles International',
    OAK:'Metropolitan Oakland International',
    ONT:'Ontario International',
    PHX:'Phoenix Sky Harbor International',
    SAN:'San Diego International',
    STL:'St Louis Lambert International',
    BNA:'Nashville International',
    FLL:'Fort Lauderdale-Hollywood International',
    HOU:'William P Hobby',
    TPA:'Tampa International',
    ABQ:'Albuquerque International Sunport',
    AUS:'Austin - Bergstrom International',
    BOI:'Boise Air Terminal',
    BUF:'Buffalo Niagara International',
    CLE:'Cleveland-Hopkins International',
    CMH:'John Glenn Columbus International',
    DTW:'Detroit Metro Wayne County',
    ELP:'El Paso International',
    GEG:'Spokane International',
    ICT:'Wichita Dwight D Eisenhower National',
    IND:'Indianapolis International',
    LIT:'Bill and Hillary Clinton Nat Adams Field',
    MCI:'Kansas City International',
    MKE:'General Mitchell International',
    MSP:'Minneapolis-St Paul International',
    MSY:'Louis Armstrong New Orleans International',
    OKC:'Will Rogers World',
    OMA:'Eppley Airfield',
    PDX:'Portland International',
    PHL:'Philadelphia International',
    PIT:'Pittsburgh International',
    RDU:'Raleigh-Durham International',
    RNO:'Reno/Tahoe International',
    SAT:'San Antonio International',
    SDF:'Louisville Muhammad Ali International',
    SEA:'Seattle/Tacoma International',
    SLC:'Salt Lake City International',
    SNA:'John Wayne Airport-Orange County',
    TUL:'Tulsa International',
    RSW:'Southwest Florida International',
    DCA:'Ronald Reagan Washington National',
    BDL:'Bradley International',
    TUS:'Tucson International',
    HNL:'Daniel K Inouye International',
    LGB:'Long Beach Airport',
    OGG:'Kahului Airport',
    BOS:'Logan International',
    DSM:'Des Moines International',
    LGA:'LaGuardia',
    ALB:'Albany International',
    BHM:'Birmingham-Shuttlesworth International',
    MEM:'Memphis International',
    MHT:'Manchester-Boston Regional',
    PVD:'Theodore Francis Green State',
    SJU:'Luis Munoz Marin International',
    GSP:'Greenville-Spartanburg International',
    IAD:'Washington Dulles International',
    JAX:'Jacksonville International',
    PBI:'Palm Beach International',
    RIC:'Richmond International',
    MAF:'Midland International Air and Space Port',
    LIH:'Lihue Airport',
    KOA:'Ellison Onizuka Kona International at Keahole',
    HRL:'Valley International',
    LBB:'Lubbock Preston Smith International',
    CHS:'Charleston AFB/International',
    CLT:'Charlotte Douglas International',
}